fullnameOverride: cert-manager
nameOverride: cert-manager
installCRDs: true
startupapicheck:
  enabled: false
controller:
  replicas: 1
  image:
    pullPolicy: IfNotPresent
  pullSecrets: []
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      memory: 256Mi
  affinity: {}
  nodeSelector: {}
  tolerations: []
  extraArgs: []
  extraEnv: []
webhook:
  replicas: 1
  image:
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      memory: 256Mi
  affinity: {}
  nodeSelector: {}
  tolerations: []
  injectAPIServerCA: true
  securePort: 10250
cainjector:
  replicas: 1
  image:
    pullPolicy: IfNotPresent

  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 100m
      memory: 256Mi
  nodeSelector: {}
  affinity: {}
  tolerations: []
ingressShim: {}